### PR TITLE
rename archive package to lake

### PR DESCRIPTION
**Pull request by alfred-landrum**
This change renames the archive package to lake, the `Archive` struct to `Lake`, and the canonical variable name for a `*Archive` from `ark` to `lk`. No other changes (api routes, metric names, etc) are changed.

### CODE REVIEW

**Comment by alfred-landrum** [comment]
I see there are still some usages of 'ark' as a variable name, will continue to search & replace.

**Comment by mccanne** [comment]
I like it!

**Review by nwt — APPROVED** [review]
This still leaves us with a grip of "archive" occurrences.
```
$ git grep -i archive | wc -l
     221
```
Do we plan to eliminate those separately?

**Comment by alfred-landrum** [comment]
> This still leaves us with a grip of "archive" occurrences.
> 
> ```
> $ git grep -i archive | wc -l
>      221
> ```
> 
> Do we plan to eliminate those separately?

Yes - many of those left are references to the api structs, or the storage kind, which will take some Brim coordination & migration to manage.

**Pull request merged**
