### PR TITLE
create proc.Cutter from proc.Cut so it can be reused by zdx

### PR DESCRIPTION
**Pull request by mccanne**

### CODE REVIEW

**Comment by henridf** [comment]
Are there any substantive changes to the proc.Cutter or is just just a move/rename? (hard to tell from the single commit)

**Comment by mccanne** [comment]
> Are there any substantive changes to the proc.Cutter or is just just a move/rename? (hard to tell from the single commit)

No change at all.  Just a re-factor so cutter.Cut() can be called an a sequence of zng.Records without the rest of the proc plumbing.  I might have fixed a Go nit or two but no semantics change.

**Comment by henridf** [comment]
> No change at all. Just a re-factor so cutter.Cut() can be called an a sequence of zng.Records without the rest of the proc plumbing. I might have fixed a Go nit or two but no semantics change.

That makes things easier!

**Comment by mccanne** [comment]
> > No change at all. Just a re-factor so cutter.Cut() can be called an a sequence of zng.Records without the rest of the proc plumbing. I might have fixed a Go nit or two but no semantics change.
> 
> That makes things easier!

Thanks, I should I have pointed this out in the first place...

**Comment by henridf** [comment]
> Thanks, I should I have pointed this out in the first place...

Or let the commit sequence do the talking and have a one commit that does any changes in place, and one commit that does the move. Like the two latter commits of #715 🤓 😎

**Pull request merged**
