### PR TITLE
Remove ast.ReduceProc

### LINKED ISSUE #1123: Remove ast.ReduceProc
Change zql.peg to just emit an ast.GroupByProc for bare reducers and remove ast.ReduceProc.

This is a follow-on to #1122 as mentioned in https://github.com/brimsec/zq/pull/1122#discussion_r473273856

### PR DESCRIPTION
**Pull request by henridf**
I should just have done this along with #1122... thought it would be longer. Anyway, here it is!

closes #1123

### CODE REVIEW

**Comment by alfred-landrum** [comment]
@henridf : if you haven't already, would you please run the Brim integration tests against this change?

**Comment by henridf** [comment]
@alfred-landrum i dispensed myself of running them after having found no `ReduceProc` anywhere the brim repo; but i'll run it now.

**Comment by henridf** [comment]
@alfred-landrum : I ran Brim itest on my host (having done `npm install https://github.com/brimsec/zq#remove-reduceproc-ast && npm install`) and had these five errors (everything else passed):

    ✕ pcap button downloads deterministically-formed pcap file (30211ms)                                                                                                                                    
    ✕ Brim starts when a Zar space is present (38538ms)                                                                                                                                                     
    ✕ clicking the export button (15379ms)
    ✕ ingest of sample.pcapng (30641ms)
    ✕ ingest of sample.tsv (25735ms)

I haven't run itest locally in quite a while; I'm going to try running it with zq master to see if the errors go away.

**Comment by henridf** [comment]
@alfred-landrum Brim integration test passed here: https://github.com/brimsec/brim/pull/1013

**Pull request merged**
