### PR TITLE
Time index wip

### PR DESCRIPTION
**Pull request by aswan**
This is a rebase to recent master of @mccanne's simple-time-index-rebase branch plus a bit of hacking on it.
It needs testing and a zqd config switch to enable/disable it before merging, but here it is for early feedback.

### CODE REVIEW

**Comment by alfred-landrum** [comment]
How about if the index creation happens inside space.OpenFile(all.bzng), and gets cleared in space.CreateFile? 

OpenFile(all.bzng) would become "OpenZng" that returns a zng reader. Inside OpenZng, use the Space struct to see if we have index offsets, and if not, read the whole file there, store the index offsets as a member of the Space struct. CreateFile(all.bzng) becomes "CreateZng" that clears the index.

We're working towards keeping more state in the `Space` struct, so keeping the index there is probably the best place.

**Comment by aswan** [comment]
> How about if the index creation happens inside space.OpenFile(all.bzng), and gets cleared in space.CreateFile?
> 
> OpenFile(all.bzng) would become "OpenZng" that returns a zng reader. Inside OpenZng, use the Space struct to see if we have index offsets, and if not, read the whole file there, store the index offsets as a member of the Space struct. CreateFile(all.bzng) becomes "CreateZng" that clears the index.

Maybe I'm misunderstanding the suggestion but the way this works right now, the first reader gets no indexing benefits so it has to scan the whole file, and it builds the index while doing this.  But there's no extra pass over the file for the purpose of constructing the index.  I think that's a useful optimization but it would be more awkward to manage with the code to manage indexes outside of index.go.

**Comment by alfred-landrum** [comment]
> Maybe I'm misunderstanding the suggestion but the way this works right now, the first reader gets no indexing benefits so it has to scan the whole file, and it builds the index while doing this. But there's no extra pass over the file for the purpose of constructing the index. I think that's a useful optimization but it would be more awkward to manage with the code to manage indexes outside of index.go.

Ok, putting aside the extra pass: I do think the index should be stored as a field on the `Space` struct, and not as in a package level map in bzngio. That's where it will eventually be managed, when we want to persist it along with other indices on the space.

**Comment by aswan** [comment]
Rebased onto @mccane's bzng stream io branch.  Still has some obsolete names that need to be cleaned up.  Also, this touches zqd space and search in a way that might conflict with ongoing cleanup that @henridf and/or @mattnibs are doing, I can separate some of the refactoring there if it looks like we're headed for a collision...

**Comment by mccane** [comment]
> Rebased onto @mccane's bzng stream io branch. Still has some obsolete names that need to be cleaned up. Also, this touches zqd space and search in a way that might conflict with ongoing cleanup that @henridf and/or @mattnibs are doing, I can separate some of the refactoring there if it looks like we're headed for a collision...

@aswan I think you meant @mccanne, not @mccane ...

**Pull request closed without merging**
