### PR TITLE
Add Parquet writer and rework Parquet reader

### LINKED ISSUE #2167: Support parquet output
Add a parquet writer to the parquetio package, and add the parquet output format option to zq.

### LINKED ISSUE #2263: Change parquet reader implementation to use fraugster/parquet-go
We feel like the fraugster/parquet-go is a better choice for parquet input as well as output, so we'll update the parquet reader to use this library.

### PR DESCRIPTION
**Pull request by nwt**
\* Add zio/parquetio.Writer.  
\* Add Parquet boomerang tests.  
\* Rework zio/parquetio.Reader so boomerang tests pass.

This implementation uses github.com/brimsec/parquet-go, a fork of  
github.com/fraugster/parquet-go with bug fixes and a larger set of  
characters allowed in column names.

For simplicity, the new reader and writer use parquet-go interfaces that  
require multiple memory allocations per record.  This is a step backward  
from the current reader, but one that can be addressed later.

Closes #2167.

Closes #2263.

### CODE REVIEW

**Comment by mccanne** [comment]
Nice job.

**Comment by mccanne** [comment]
Can it boomerang using the parquet reader?

**Comment by philrz** [comment]
Boomerang causes a panic at the moment. I couldn't help myself and tried when @nwt showed the first working example yesterday. Given the celebratory nature of the moment, I didn't see much upside in that being the first thing I said. 😄 

```
zq-sample-data/zeek-default$ zq -version
Version: v0.29.0-67-g299de516

zq-sample-data/zeek-default$ zq -f parquet rfb.log.gz > /tmp/rfb.parquet

zq-sample-data/zeek-default$ zq -z -i parquet /tmp/rfb.parquet 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17320a5]

goroutine 1 [running]:
github.com/brimsec/zq/zio/parquetio.(*Reader).buildColumns(0xc00037fa40, 0x0, 0x0, 0x0, 0x1fd0f00, 0x0, 0xc00019f3e0)
	/Users/phil/work/zq/zio/parquetio/reader.go:250 +0x165
github.com/brimsec/zq/zio/parquetio.(*Reader).initialize(0xc00037fa40, 0xc000130708, 0x0, 0x0, 0x0, 0x0, 0x10, 0x7ffeefbff9e9)
	/Users/phil/work/zq/zio/parquetio/reader.go:160 +0xa8
github.com/brimsec/zq/zio/parquetio.NewReader(0x1b35a40, 0xc00038d160, 0xc000130708, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00019f4d8)
	/Users/phil/work/zq/zio/parquetio/reader.go:147 +0xd6
github.com/brimsec/zq/zio/detector.OpenParquet(0xc000130708, 0x19aa7e7, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbff9e9, 0x10, ...)
	/Users/phil/work/zq/zio/detector/file.go:59 +0x127
github.com/brimsec/zq/zio/detector.OpenFileWithContext(0x1b31040, 0xc000134008, 0xc000130708, 0x7ffeefbff9e9, 0x10, 0x7ffeefbff9e1, 0x7, 0x1, 0x80000, 0xa00000, ...)
	/Users/phil/work/zq/zio/detector/file.go:37 +0x2bb
github.com/brimsec/zq/zio/detector.OpenFile(...)
	/Users/phil/work/zq/zio/detector/file.go:26
github.com/brimsec/zq/cli/inputflags.(*Flags).Open(0xc000219a20, 0xc000130708, 0xc000136040, 0x1, 0x1, 0x1b1e801, 0xc0003a9500, 0x0, 0x0, 0x1f60c20, ...)
	/Users/phil/work/zq/cli/inputflags/flags.go:91 +0x198
main.(*Command).Run(0xc000219a00, 0xc000136040, 0x1, 0x1, 0x0, 0x0)
	/Users/phil/work/zq/cmd/zq/zq.go:159 +0x5b1
github.com/mccanne/charm.(*instance).run(0xc0002fc180, 0xc000136010, 0x4, 0x4, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x293
github.com/mccanne/charm.(*Spec).ExecRoot(0x1fc69a0, 0xc000136010, 0x4, 0x4, 0xc00019ff78, 0x1007f65, 0xc00010e058, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x96
main.main()
	/Users/phil/work/zq/cmd/zq/main.go:9 +0x85
```

**Review by mccanne — APPROVED** [review]
Excellent work!

**Comment by nwt** [comment]
My plan for ZSON -> Parquet -> Parquet -> ZSON in the boomerang tests was half-baked. There's just too much of the ZNG type system that Parquet can't preserve (viz., type aliases, the set type, and a bunch of primitive types) to make it feasible.

**Pull request merged**
